services:
    kodus-service-ast:
        image: kodus/service-ast:latest
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile.dev
        ports:
            - ${API_AST_PORT}:${API_AST_PORT}
            - ${API_TASK_PORT}:${API_TASK_PORT}
            - 5001:5001
            - 9300:9300
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - .:/usr/src/app
        networks:
            - kodus-backend-services

networks:
    kodus-backend-services:
        external: true
