services:
    kodus-ast:
        image: kodus/service-ast:latest
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile.dev
        ports:
            - ${API_PORT}:${API_PORT}
            - 9300:9300
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - .:/usr/src/app:delegated
            - /usr/src/app/node_modules
        networks:
            - kodus-backend-services

networks:
    kodus-backend-services:
        external: true
