services:
    kodus-service-ast-api:
        image: kodus/service-ast:latest
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile.dev
        ports:
            - ${API_PORT}:${API_PORT}
            - 5001:5001
            - 9300:9300 # debug
            - 9301:9301 # test debug
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./src:/usr/src/app/src
            - ./package.json:/usr/src/app/package.json
            - ./tsconfig.json:/usr/src/app/tsconfig.json
            - ./nest-cli.json:/usr/src/app/nest-cli.json
            - ./.swcrc:/usr/src/app/.swcrc
            - /usr/src/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - kodus-backend-services
            - shared-network

    kodus-service-ast-worker:
        image: kodus/service-ast:latest
        container_name: ${CONTAINER_NAME}-worker
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile.dev
        command: ["yarn", "start:worker:dev"]
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./src:/usr/src/app/src
            - ./package.json:/usr/src/app/package.json
            - ./tsconfig.json:/usr/src/app/tsconfig.json
            - ./nest-cli.json:/usr/src/app/nest-cli.json
            - ./.swcrc:/usr/src/app/.swcrc
            - /usr/src/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - kodus-backend-services
            - shared-network
        depends_on:
            - kodus-service-ast-api

networks:
    kodus-backend-services:
        external: true
    shared-network:
        external: true
