services:
    kodus-ast:
        image: ${IMAGE_NAME_PROD}
        container_name: ${CONTAINER_NAME}
        logging:
            options:
                max-size: '200m'
                max-file: '10'
        ports:
            - 3002:3002
        env_file:
            - .env.prod
        environment:
            - ENV=production
            - API_NODE_ENV=production
        restart: unless-stopped
        volumes:
            - log_volume:/app/logs

volumes:
    log_volume:
