services:
    kodus-service-ast:
        image: kodus/service-ast:latest
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: DockerFiles/Dockerfile.dev
        ports:
            - ${API_PORT}:${API_PORT}
            - 5001:5001
            - 9300:9300 # debug
            - 9301:9301 # test debug
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - kodus-backend-services

networks:
    kodus-backend-services:
        external: true
