// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: kodus/common/chunk.proto

/* eslint-disable */

export const protobufPackage = "kodus.common";

export interface kodusRPCChunkResponse {
  chunk: string;
}

export const KODUS_COMMON_PACKAGE_NAME = "kodus.common";
