// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: kodus/common/response.proto

/* eslint-disable */

export const protobufPackage = "kodus.common";

export interface kodusRPCGrpcError {
  message: string;
  code: number;
}

export interface kodusRPCGrpcResponse {
  message: string;
  success: boolean;
  errors: kodusRPCGrpcError[];
}

export const KODUS_COMMON_PACKAGE_NAME = "kodus.common";
