FROM --platform=linux/amd64 node:22.14.0

ENV NODE_ENV=development
ENV NODE_OPTIONS=--max-old-space-size=4096
ENV PORT=3002
ENV API_HEALTH_PORT=5001

WORKDIR /usr/src/app

# Instala dependências do sistema
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    python3 \
    make \
    g++ \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copia apenas os arquivos necessários para instalar as dependências
COPY package.json yarn.lock ./

# Instala as dependências
RUN yarn install --network-timeout 600000

# Expõe as portas necessárias
EXPOSE ${PORT} ${API_HEALTH_PORT} 9300

# Comando para iniciar em modo de desenvolvimento
CMD ["yarn", "start:dev"]
