name: Build and Publish Docker Images

on:
    release:
        types: [published]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
            AR_REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev
            GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
            REPOSITORY: kodus-images
            IMAGE: kodus-service-ast-prod
            IMAGE_TAG_SHA: ${{ github.sha }}
            IMAGE_TAG_VERSION: ${{ github.event.release.tag_name }}

        steps:
            - uses: actions/checkout@v4

            - name: Authenticate to GCP
              run: |
                  echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json
                  gcloud auth activate-service-account --key-file=$HOME/gcp-key.json --project=$GCP_PROJECT

            - name: Configure Docker for Artifact Registry
              run: |
                  gcloud auth configure-docker $AR_REGISTRY --quiet

            - name: Build and Push Docker Image
              run: |
                  docker build \
                    --build-arg RELEASE_VERSION=$IMAGE_TAG_VERSION \
                    --build-arg API_CLOUD_MODE=true \
                    -f DockerFiles/Dockerfile.prod \
                    -t $AR_REGISTRY/$GCP_PROJECT/$REPOSITORY/$IMAGE:$IMAGE_TAG_SHA \
                    -t $AR_REGISTRY/$GCP_PROJECT/$REPOSITORY/$IMAGE:$IMAGE_TAG_VERSION .
                  docker push $AR_REGISTRY/$GCP_PROJECT/$REPOSITORY/$IMAGE:$IMAGE_TAG_SHA
                  docker push $AR_REGISTRY/$GCP_PROJECT/$REPOSITORY/$IMAGE:$IMAGE_TAG_VERSION
